version: "3.8"

services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql_8_0_39
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Zjajtm0724!"
      MYSQL_DATABASE: commerce
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - commerce-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "8081:8081"
    environment:
      NODE_ENV: production
      MYSQL_DB: commerce
      MYSQL_DB_USER: root
      MYSQL_DB_HOST: mysql
      MYSQL_DB_PASSWORD: "Zjajtm0724!"
      APP_PORT: "8081"
    depends_on:
      - mysql
    networks:
      - commerce-network
    restart: always  

volumes:
  mysql-data:

networks:
  commerce-network:
